$("document").ready(() => {
  $("#pass, #cpass").on("keyup", function () {
    if ($("#cpass").val() == "" && $("#pass").val() == "") {
      $("#eye").css({ color: "black" });
    }
    if (
      $("#cpass").val() == $("#pass").val() &&
      $("#cpass").val() != "" &&
      $("#pass").val() != ""
    ) {
      $("#eye").css({ color: "green" });
    }
    if ($("#cpass").val() != $("#pass").val()) {
      $("#eye").css({ color: "red" });
    }
  });

  $("#eye").mousedown(() => {
    $("#cpass").attr("type", "text");
  });
  $("#eye").mouseup(() => {
    $("#cpass").attr("type", "password");
  });

  $("#pass").mouseup(() => {
    if ($("#pass").length < 8) {
      $("#pass").css({ borderColor: "red" });
      if ($("#span").length == 0) {
        $("#span")
          .append("Password must be of at least 8 char")
          .css({ color: "red" });
      }
    }
  });

  var availableTags = [
    "ActionScript",
    "AppleScript",
    "Asp",
    "BASIC",
    "C",
    "C++",
    "Clojure",
    "COBOL",
    "ColdFusion",
    "Erlang",
    "Fortran",
    "Groovy",
    "Haskell",
    "Java",
    "JavaScript",
    "Lisp",
    "Perl",
    "PHP",
    "Python",
    "Ruby",
    "Scala",
    "Scheme",
    "Android",
    "Jquery",
  ];
  availableTags.forEach((element) => {
    $("#tumnya").append("<option>" + element + "</option>");
    console.log(element);
  });

  $("#tumnya").select2({
    tags: true,
    tokenSeparators: [",", " "],
  });

  var city = [
    "",
    "Adoni",
    "Agartala",
    "Agra",
    "Ahmedabad",
    "Ahmednagar",
    "Aizawl",
    "Ajmer",
    "Akola",
    "Alappuzha",
    "Aligarh",
    "Allahabad",
    "Alwar",
    "Amaravati",
    "Ambala",
    "Ambarnath",
    "Ambattur",
    "Amravati",
    "Amritsar",
    "Amroha",
    "Anand",
    "Anantapur",
    "Arrah",
    "Asansol",
    "Aurangabad",
    "Aurangabad",
    "Avadi",
    "Bahraich",
    "Ballia",
    "Bally",
    "Bangalore",
    "Baranagar",
    "Barasat",
    "Bardhaman",
    "Bareilly",
    "Bathinda",
    "Beed",
    "Begusarai",
    "Belgaum",
    "Bellary",
    "Berhampore",
    "Berhampur",
    "Bettiah",
    "Bhagalpur",
    "Bhalswa Jahangir Pur",
    "Bharatpur",
    "Bhatpara",
    "Bhavnagar",
    "Bhilai",
    "Bhilwara",
    "Bhimavaram",
    "Bhind",
    "Bhiwandi",
    "Bhiwani",
    "Bhopal",
    "Bhubaneswar",
    "Bhusawal",
    "Bidar",
    "Bidhannagar",
    "Bihar Sharif",
    "Bijapur",
    "Bikaner",
    "Bilaspur",
    "Bokaro",
    "Bongaigaon",
    "Bulandshahr",
    "Burhanpur",
    "Buxar",
    "Chandigarh",
    "Chandrapur",
    "Chapra",
    "Chennai",
    "Chinsurah",
    "Chittoor",
    "Coimbatore",
    "Cuttack",
    "Danapur",
    "Darbhanga",
    "Davanagere",
    "Dehradun",
    "Dehri",
    "Delhi",
    "Deoghar",
    "Dewas",
    "Dhanbad",
    "Dharmavaram",
    "Dhule",
    "Dibrugarh",
    "Dindigul",
    "Durg",
    "Durgapur",
    "Eluru",
    "Erode",
    "Etawah",
    "Faridabad",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Gandhidham",
    "Gandhinagar",
    "Gangtok",
    "Gaya",
    "Ghaziabad",
    "Giridih",
    "Gopalpur",
    "Gorakhpur",
    "Gudivada",
    "Gulbarga",
    "Guna",
    "Guntakal",
    "Guntur",
    "Gurgaon",
    "Guwahati",
    "Gwalior",
    "Hajipur",
    "Haldia",
    "Hapur",
    "Haridwar",
    "Hazaribagh",
    "Hindupur",
    "Hospet",
    "Hosur",
    "Howrah",
    "Hubli–Dharwad",
    "Hyderabad",
    "Ichalkaranji",
    "Imphal",
    "Indore",
    "Jabalpur",
    "Jaipur",
    "Jalandhar",
    "Jalgaon",
    "Jalna",
    "Jamalpur",
    "Jammu",
    "Jamnagar",
    "Jamshedpur",
    "Jaunpur",
    "Jehanabad",
    "Jhansi",
    "Jodhpur",
    "Jorhat",
    "Junagadh",
    "Kadapa",
    "Kakinada",
    "Kalyan-Dombivli",
    "Kamarhati",
    "Kanpur",
    "Karaikudi",
    "Karawal Nagar",
    "Karimnagar",
    "Karnal",
    "Katihar",
    "Katni",
    "Kavali",
    "Khammam",
    "Khandwa",
    "Kharagpur",
    "Khora, Ghaziabad",
    "Kirari Suleman Nagar",
    "Kishanganj",
    "Kochi",
    "Kolhapur",
    "Kolkata",
    "Kollam",
    "Korba",
    "Kota",
    "Kottayam",
    "Kozhikode",
    "Kulti",
    "Kumbakonam",
    "Kurnool",
    "Latur",
    "Loni",
    "Lucknow",
    "Ludhiana",
    "Machilipatnam",
    "Madanapalle",
    "Madhyamgram",
    "Madurai",
    "Mahbubnagar",
    "Maheshtala",
    "Malda",
    "Malegaon",
    "Mangalore",
    "Mango",
    "Mathura",
    "Mau",
    "Medininagar",
    "Meerut",
    "Mehsana",
    "Mira-Bhayandar",
    "Miryalaguda",
    "Mirzapur",
    "Moradabad",
    "Morbi",
    "Morena",
    "Motihari",
    "Mumbai",
    "Munger",
    "Muzaffarnagar",
    "Muzaffarpur",
    "Mysore",
    "Nadiad",
    "Nagaon",
    "Nagercoil",
    "Nagpur",
    "Naihati",
    "Nanded",
    "Nandyal",
    "Nangloi Jat",
    "Narasaraopet",
    "Nashik",
    "Navi Mumbai",
    "Nellore",
    "New Delhi",
    "Nizamabad",
    "Noida",
    "North Dumdum",
    "Ongole",
    "Orai",
    "Ozhukarai",
    "Pali",
    "Pallavaram",
    "Panchkula",
    "Panihati",
    "Panipat",
    "Panvel",
    "Parbhani",
    "Patiala",
    "Patna",
    "Phagwara",
    "Phusro",
    "Pimpri-Chinchwad",
    "Pondicherry",
    "Proddatur",
    "Pudukkottai",
    "Pune",
    "Purnia",
    "Raebareli",
    "Raichur",
    "Raiganj",
    "Raipur",
    "Rajahmundry",
    "Rajkot",
    "Rajpur Sonarpur",
    "Ramagundam",
    "Ramgarh",
    "Rampur",
    "Ranchi",
    "Ratlam",
    "Raurkela Industrial Township",
    "Rewa",
    "Rohtak",
    "Rourkela",
    "Sagar",
    "Saharanpur",
    "Saharsa",
    "Salem",
    "Sambalpur",
    "Sambhal",
    "Sangli-Miraj & Kupwad",
    "Sasaram",
    "Satara",
    "Satna",
    "Secunderabad",
    "Serampore",
    "Shahjahanpur",
    "Shimla",
    "Shimoga",
    "Shivpuri",
    "Sikar",
    "Silchar",
    "Siliguri",
    "Singrauli",
    "Sirsa",
    "Siwan",
    "Solapur",
    "Sonipat",
    "South Dumdum",
    "Sri Ganganagar",
    "Srikakulam",
    "Srinagar",
    "Sultan Pur Majra",
    "Surat",
    "Surendranagar Dudhrej",
    "Suryapet",
    "Tadepalligudem",
    "Tadipatri",
    "Tenali",
    "Tezpur",
    "Thane",
    "Thanjavur",
    "Thiruvananthapuram",
    "Thoothukudi",
    "Thrissur",
    "Tinsukia",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tirupati",
    "Tiruppur",
    "Tiruvottiyur",
    "Tumkur",
    "Udaipur",
    "Udupi",
    "Ujjain",
    "Ulhasnagar",
    "Uluberia",
    "Unnao",
    "Vadodara",
    "Varanasi",
    "Vasai-Virar",
    "Vellore",
    "Vijayanagaram",
    "Vijayawada",
    "Visakhapatnam",
    "Warangal",
    "Yamunanagar",
  ];
  $("#city").select2({
    data: city,
  });

  // validate signup form on keyup and submit
  var validator = $("form[name='register']").validate({
    rules: {
      name: "required",
      username: {
        required: true,
        minlength: 2,
      },
      pass: {
        required: true,
        minlength: 5,
      },
      cpass: {
        required: true,
        minlength: 5,
        equalTo: "#pass",
      },
      email: {
        required: true,
        email: true,
      },
    },
    messages: {
      name: "Enter your name",

      pass: {
        required: "Provide a password",
        minlength: jQuery.validator.format("Enter at least {0} characters"),
      },
      cpass: {
        required: "Repeat your password",
        minlength: jQuery.validator.format("Enter at least {0} characters"),
        equalTo: "Enter the same password as above",
      },
      email: {
        required: "Please enter a valid email address",
        minlength: "Please enter a valid email address",
        remote: jQuery.validator.format("{0} is already in use"),
      },
    },
    submitHandler: function (form) {
      form.submit();
    },
  });
});
