$('document').ready(()=>{
    $('#red').click(()=>{
        $('button').removeClass('green');
        $('button').addClass('gray');
        $('#red').removeClass('gray');
        $('#red').addClass('green');
        $('.red').show();
        $('.orange').hide();
        $('.yellow').hide();
    })
    $('#orange').click(()=>{
        $('button').removeClass('green');
        $('button').addClass('gray');
        $('#orange').removeClass('gray');
        $('#orange').addClass('green');
        $('.orange').show();
        $('.red').hide();
        $('.yellow').hide();
    })
    $('#yellow').click(()=>{
        $('button').removeClass('green');
        $('button').addClass('gray');
        $('#yellow').removeClass('gray');
        $('#yellow').addClass('green');
        $('.yellow').show();
        $('.red').hide();
        $('.orange').hide();
    })
    $('#all').click(()=>{
        $('button').removeClass('green');
        $('button').addClass('gray');
        $('#all').removeClass('gray');
        $('#all').addClass('green');
        $('.red').show();
        $('.orange').show();
        $('.yellow').show();
    })
})